<footer><!--footer-->
    <section class="wrapper">
        <div class="left-col">
            <p>&copy; Legalmag, 2012</p>
            <p>Все права защищены.</p>
            <p style="margin: 20px 0 5px 0;"><a href="">Условия использования</a></p>
            <a href="">Регламент техподдержки</a>
        </div>
        <div class="right-col">
            <nav>
                <ul>
                    <li><a href="/o_proekte.html">О проекте </a></li>
                    <li><a href="/usloviya_ispolzovaniya.html">Условия использования</a></li>
                    <li class="active"><a href="/dlya_investorov.html">Для инвесторов</a></li>
                    <li><a href="/bezopasnost.html">Безопасность </a></li>
                    <li><a href="/kontaktyi.html">Контакты</a></li>
                </ul>
            </nav>
            <div id="paySystems"></div>
        </div>
    </section>
</footer>