<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->partial('inc.head.phtml'); ?>
    </head>

    <body>
        <section id="body">
            <section id="content"><!--content-->
                <div class="wrapper">
                    <div id="regForm">
                        <a href="/"><img src="/design/img/logo.png" alt="LEGALMAG" class="logo"></a>
                        <?php echo $this->layout()->content; ?>                        
                             <script type="text/javascript">
        					$('#loginButton').unbind("click").click(function(){        					
            					if (!$('#enterForm .form .form-error').size()) {
                					$.get('http://<?php echo $_SERVER['SERVER_NAME'].Rastor_Url::get('login_result'); ?>', $('#enterForm form').serializeArray(), function(data){
                    				if (data == '1') {
                        				document.location = '<?php echo Rastor_Url::get('default'); ?>';
                    				} else {
                        				$('#loginpanel .form').append('<div class="form-error">Вы ввели неверный пароль или адрес электронной почты</div>');
                        				$('#loginpanel .form .form-error').fadeOut(3000, function() {
                            					$(this).remove();
                        	   				});
                    					}
                					});
            					}
        				});
    </script>                            
                        </div>
                    </div>
                </div>
            </section>
        </section>
    </body>
</html>