<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->partial('inc.head.phtml'); ?>
    </head>
    <body>
        <section id="body">
            <?php echo $this->partial('inc.header.phtml'); ?>
            <div class="clear">&nbsp;</div>

           <section id="content"><!--content-->
			<div class="wrapper">
				<?php echo $this->layout()->content ?>
			</div>
		</section>

            <div class="clear">&nbsp;</div>
            <div id="rasporka"></div>

        </section><!--/body-wrapper-->

        <?php echo $this->partial('inc.footer.phtml'); ?>
    </body>
</html>
