<style>
  #tabss li a {
float: left;
width: 100%;
text-align: center;
height: 29px;
padding: 8px 0px 0 0;
text-decoration: none;  
  }
#tabss li {
border-left: 0;
margin-left: 1px;
border: 1px solid #ACA99F;
border-bottom: 0;
background: white;
font-weight: bold;
font-size: 16px;
color: #00488C;

width: 32.1%;
list-style: none;
float: left;
margin: 0;
padding: 0;
white-space: nowrap;
font-style: italic;

border: 1px solid #ACA99F;
border-top: 0;
background: white;
color: #333;

border: 1px solid #ACA99F;
border-bottom: 0;
background: white;
font-weight: bold;
font-size: 16px;
color: #00488C;

border-top-right-radius: 10px;

</style>

<div id="tabss">
    <ul>
        <li><a href="http://legalmag.com/profile/commercial/statistic">Статистика</a></li>
        <li><a href="http://legalmag.com/profile/commercial/views">Настройки показов</a></li>
        <li><a href="3">Виды обьявлений</a></li>
    </ul>
</div>
привед