<section id="right-col">
					<div class="questionWrapper">
						<div class="thankYouHead">
							<p class="first">Спасибо за Ваш вопрос!</p>
						</div>
						<div class="thankYouBody">
							<p class="first">Ваш вопрос будет направлен выбранным вами юристам. О поступлении ответов мы известим вас в письме.</p>
						</div>
					</div>
					<div class="wrapper2">
						<p class="first">Вы можете перевести свой вопрос в категорию платных.</p>
						<p>Вы можете сделать этот вопрос платным и доступным для всех юристов. Вы сами определяете желаемую стоимость вопроса. Юристы отвечают на все платные вопросы.</p>
						<div class="job-amount m30">
							<p class="text">Укажите желаемую стоимость:</p>
							<input type="text" class="amount" maxlength="5" placeholder="100">
							<p>рублей</p>
							<input type="submit" class="buttonPay" value="Оплатить">
						</div>
					</div>
				</section>
