<div class="wrapper profile">
	<?php //Zend_Debug::dump($this->paidWA);die; ?>
    <div class="head">
        <ul >
            <li class="active"><a href="<?php echo Rastor_Url::get('default') ?>">Вопросы</a></li>
            <li><a href="<?php echo Rastor_Url::get('jobs') ?>">Работа</a></li>
        </ul>
        <span class="headSep">&nbsp;</span>
    </div>
    <section class="body">
    	<?php if(count($this->paidWA)>0)
    	foreach ($this->paidWA as $record) { ?>
	<?php //Zend_Debug::dump($record);die; ?>
        <div class="question">
            <table>
                <tr>
                    <td rowspan="2" class="first">
                        <p  class="qSubscribe"></p>
                        <span>3</span>
                        <a href="">Подписаться</a>
                    </td>
                    <td class="title"><a href="<?php echo Rastor_Url::get('question_view', array('id' => $record->id)); ?>"><?php echo $record->name; ?></a></td>
                </tr>
                <tr>
                    <td class="text"><a href="<?php echo Rastor_Url::get('question_view', array('id' => $record->id)); ?>"><?php echo $record->content; ?></a></td>
                </tr>
                <tr>
                    <td rowspan="2"><?php if ($record->paid == 1) { ?><p class="price"><?php echo $record->price; ?> <img src="/design/img/_qPrice.png " alt="Цена в рублях" style="width: 11px;height: 12px;"></p><?php } ?></td>
                    <td class="place">Месторасположение: <strong><?php echo $record->user_city; ?></strong></td>
                </tr>
                <?php if (count($this->tags[$record->id])) { ?>
                <tr>
                    <td class="tags">Теги: <?php echo implode(', ', $this->tags[$record->id]) ?></td>
                </tr>
                <?php } ?>
            </table>
            <div class="summary">
                <p class="time"><?php echo $this->RastorDate($record->date); ?> назад</p>
                <p class="views"><?php echo $record->views.' '.$this->translate(array('просмотр', 'просмотра', 'просмотров', $record->views, 'ru')); ?></p>
                <p class="answers"><?php echo $record->answers.' '.$this->translate(array('ответ', 'ответа', 'ответов', $record->answers, 'ru')); ?></p>
                <p class="author">Автор: <a href="/user/<?php echo $record->user_id; ?>"><?php echo $record->user_name; ?></a></p>
                <p class="privatMessage"><a href="/message/<?php echo $record->user_id; ?>">личное сообщение</a></p>
            </div>
            <div class="clear ">&nbsp;</div>
        </div>
        <?php } ?>
        <?php foreach ($this->paginator as $record) { ?>
	<?php //Zend_Debug::dump($record);die; ?>
        <div class="question">
            <table>
                <tr>
                    <td rowspan="2" class="first">
                        <p  class="qSubscribe"></p>
                        <span>3</span>
                        <a href="">Подписаться</a>
                    </td>
                    <td class="title"><a href="<?php echo Rastor_Url::get('question_view', array('id' => $record->id)); ?>"><?php echo $record->name; ?></a></td>
                </tr>
                <tr>
                    <td class="text"><a href="<?php echo Rastor_Url::get('question_view', array('id' => $record->id)); ?>"><?php echo $record->content; ?></a></td>
                </tr>
                <tr>
                    <td rowspan="2"><?php if ($record->paid == 1) { ?><p class="price"><?php echo $record->price; ?> <img src="/design/img/_qPrice.png " alt="Цена в рублях" style="width: 11px;height: 12px;"></p><?php } ?></td>
                    <td class="place">Месторасположение: <strong><?php echo $record->user_city; ?></strong></td>
                </tr>
                <?php if (count($this->tags[$record->id])) { ?>
                <tr>
                    <td class="tags">Теги: <?php echo implode(', ', $this->tags[$record->id]) ?></td>
                </tr>
                <?php } ?>
            </table>
            <div class="summary">
                <p class="time"><?php echo $this->RastorDate($record->date); ?> назад</p>
                <p class="views"><?php echo $record->views.' '.$this->translate(array('просмотр', 'просмотра', 'просмотров', $record->views, 'ru')); ?></p>
                <p class="answers"><?php echo $record->answers.' '.$this->translate(array('ответ', 'ответа', 'ответов', $record->answers, 'ru')); ?></p>
                <p class="author">Автор: <a href="/user/<?php echo $record->user_id; ?>"><?php echo $record->user_name; ?></a></p>
                <p class="privatMessage"><a href="/message/<?php echo $record->user_id; ?>">личное сообщение</a></p>
            </div>
            <div class="clear ">&nbsp;</div>
        </div>
        <?php } ?>
    </section>
</div>
